name: pdf_password_manager
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=3.3.0"

dependencies:
  dart_pdf_reader:
    git:
      url: https://github.com/NicolaVerbeeck/dart_pdf_reader.git
      ref: f12f68fc07eca8e5095c88d1c5a1b1055d5ab4d5
  flutter:
    sdk: flutter
  path: ^1.9.0
  plugin_platform_interface: ^2.0.2
  # pdf: ^3.11.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
# flutter:
#   plugin:
#     platforms:
#       android:
#         package: com.example.pdf_password_manager
#         pluginClass: PdfPasswordManagerPlugin
# some_platform:
#   pluginClass: somePluginClass
